// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/people/public_services.proto

package people

import (
	common "github.com/shubamakabra/MagnusBox/golang/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_people_public_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_people_public_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_people_public_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetPersonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPersonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetPersonResponse_Person
	//	*GetPersonResponse_Error
	Result isGetPersonResponse_Result `protobuf_oneof:"result"`
}

func (x *GetPersonResponse) Reset() {
	*x = GetPersonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_people_public_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonResponse) ProtoMessage() {}

func (x *GetPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_people_public_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonResponse.ProtoReflect.Descriptor instead.
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_people_public_services_proto_rawDescGZIP(), []int{1}
}

func (m *GetPersonResponse) GetResult() isGetPersonResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetPersonResponse) GetPerson() *Person {
	if x, ok := x.GetResult().(*GetPersonResponse_Person); ok {
		return x.Person
	}
	return nil
}

func (x *GetPersonResponse) GetError() *common.Error {
	if x, ok := x.GetResult().(*GetPersonResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetPersonResponse_Result interface {
	isGetPersonResponse_Result()
}

type GetPersonResponse_Person struct {
	Person *Person `protobuf:"bytes,1,opt,name=person,proto3,oneof"`
}

type GetPersonResponse_Error struct {
	Error *common.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetPersonResponse_Person) isGetPersonResponse_Result() {}

func (*GetPersonResponse_Error) isGetPersonResponse_Result() {}

type GetNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetNumberRequest) Reset() {
	*x = GetNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_people_public_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumberRequest) ProtoMessage() {}

func (x *GetNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_people_public_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumberRequest.ProtoReflect.Descriptor instead.
func (*GetNumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_people_public_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetNumberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GetNumberResponse_Number
	//	*GetNumberResponse_Error
	Result isGetNumberResponse_Result `protobuf_oneof:"result"`
}

func (x *GetNumberResponse) Reset() {
	*x = GetNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_people_public_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumberResponse) ProtoMessage() {}

func (x *GetNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_people_public_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumberResponse.ProtoReflect.Descriptor instead.
func (*GetNumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_people_public_services_proto_rawDescGZIP(), []int{3}
}

func (m *GetNumberResponse) GetResult() isGetNumberResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GetNumberResponse) GetNumber() *Person_PhoneNumber {
	if x, ok := x.GetResult().(*GetNumberResponse_Number); ok {
		return x.Number
	}
	return nil
}

func (x *GetNumberResponse) GetError() *common.Error {
	if x, ok := x.GetResult().(*GetNumberResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isGetNumberResponse_Result interface {
	isGetNumberResponse_Result()
}

type GetNumberResponse_Number struct {
	Number *Person_PhoneNumber `protobuf:"bytes,1,opt,name=number,proto3,oneof"`
}

type GetNumberResponse_Error struct {
	Error *common.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetNumberResponse_Number) isGetNumberResponse_Result() {}

func (*GetNumberResponse_Error) isGetNumberResponse_Result() {}

var File_proto_people_public_services_proto protoreflect.FileDescriptor

var file_proto_people_public_services_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6e, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x7a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xa8, 0x01,
	0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x75, 0x62, 0x61, 0x6d, 0x61, 0x6b, 0x61,
	0x62, 0x72, 0x61, 0x2f, 0x4d, 0x61, 0x67, 0x6e, 0x75, 0x73, 0x42, 0x6f, 0x78, 0x2f, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_people_public_services_proto_rawDescOnce sync.Once
	file_proto_people_public_services_proto_rawDescData = file_proto_people_public_services_proto_rawDesc
)

func file_proto_people_public_services_proto_rawDescGZIP() []byte {
	file_proto_people_public_services_proto_rawDescOnce.Do(func() {
		file_proto_people_public_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_people_public_services_proto_rawDescData)
	})
	return file_proto_people_public_services_proto_rawDescData
}

var file_proto_people_public_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_people_public_services_proto_goTypes = []interface{}{
	(*GetPersonRequest)(nil),   // 0: people.public.GetPersonRequest
	(*GetPersonResponse)(nil),  // 1: people.public.GetPersonResponse
	(*GetNumberRequest)(nil),   // 2: people.public.GetNumberRequest
	(*GetNumberResponse)(nil),  // 3: people.public.GetNumberResponse
	(*Person)(nil),             // 4: people.Person
	(*common.Error)(nil),       // 5: common.Error
	(*Person_PhoneNumber)(nil), // 6: people.Person.PhoneNumber
}
var file_proto_people_public_services_proto_depIdxs = []int32{
	4, // 0: people.public.GetPersonResponse.person:type_name -> people.Person
	5, // 1: people.public.GetPersonResponse.error:type_name -> common.Error
	6, // 2: people.public.GetNumberResponse.number:type_name -> people.Person.PhoneNumber
	5, // 3: people.public.GetNumberResponse.error:type_name -> common.Error
	0, // 4: people.public.Person.GetPerson:input_type -> people.public.GetPersonRequest
	2, // 5: people.public.Person.GetNumber:input_type -> people.public.GetNumberRequest
	1, // 6: people.public.Person.GetPerson:output_type -> people.public.GetPersonResponse
	3, // 7: people.public.Person.GetNumber:output_type -> people.public.GetNumberResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_people_public_services_proto_init() }
func file_proto_people_public_services_proto_init() {
	if File_proto_people_public_services_proto != nil {
		return
	}
	file_proto_people_person_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_people_public_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_people_public_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_people_public_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_people_public_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_people_public_services_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetPersonResponse_Person)(nil),
		(*GetPersonResponse_Error)(nil),
	}
	file_proto_people_public_services_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetNumberResponse_Number)(nil),
		(*GetNumberResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_people_public_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_people_public_services_proto_goTypes,
		DependencyIndexes: file_proto_people_public_services_proto_depIdxs,
		MessageInfos:      file_proto_people_public_services_proto_msgTypes,
	}.Build()
	File_proto_people_public_services_proto = out.File
	file_proto_people_public_services_proto_rawDesc = nil
	file_proto_people_public_services_proto_goTypes = nil
	file_proto_people_public_services_proto_depIdxs = nil
}
